### ISSUE TITLE
Also JS?

### ISSUE THREAD

**Issue by arcodb** [BabylonJS/SummerFestival#1]
This repository and the explanation on BabylonJS (https://doc.babylonjs.com/how_to/page1) is great!
I've one problem though because I haven't learned to use TypeScript (yet). Is it possible to convert the code from .ts to .js?

**Comment by Drigax** [comment]
Sorry, while its possible to use .js code in Typescript, You can't really easily go from typescript to javascript (outside of webpack/typescript compilation tools)

If you're _REALLY_ interested in seeing the raw js code for this game, you can check the compiled bundle for the game:
https://github.com/capucat/summers-festival/blob/master/bundle.js

But I highly recommend learning the typescript syntax instead, its not too far gone from normal Javascript :)

**Comment by arcodb** [comment]
Thanks for your reply!
