### ISSUE TITLE
npm run build doesn't copy assets from publics into dist folder

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/SummerFestival#2]
we should probably add something along the lines of:

```
const CopyWebpackPlugin = require('copy-webpack-plugin');
...
...
plugins: [
        new CopyWebpackPlugin({ //uncomment for production build.
            patterns: [
                { from: 'public' }
            ]
        }),
        ...
    ],
```

to our webpack.config.js to allow for building -> installation.

I ran into a similar issue with https://github.com/Drigax/RooftopRampage_Source/blob/master/webpack.config.js where including this into our webpack configuration now breaks local webserver functionality, as the files are not where the webserver expects them I assume.

**Comment by Drigax** [comment]
closing as Won't fix, but I'm happy to fix this if anyone is hindered by this.

**Comment by kuabhish** [comment]
`CopyWebpackPlugin` and `HtmlWebpackPlugin` using them together gives error
```
ERROR in Conflict: Multiple assets emit different content to the same filename index.html
```

and with just `HtmlWebpackPlugin` i am unable to load these resources into netlify server.

and with just `CopyWebpackPlugin` got another error.. related to 404 for favicon.

**Comment by sebavan** [comment]
cc @RaananW

**Comment by RaananW** [comment]
i'll look into that. reopening to keep track

**Comment by RaananW** [comment]
oh, i just realized - we don't have both, you are adding it and you have an issue.

I just changed the webpack configuration to work with both.
