### ISSUE TITLE
How where you able to use github pages with you game?

### ISSUE THREAD

**Issue by EcoEditor** [BabylonJS/SummerFestival#3]
Hello

This is more of a question.
I have a project following this tutorial: https://doc.babylonjs.com/guidedLearning/createAGame which is based on your project.
I want to be able to open the project using github.io - github pages, as same as you did on your page:
![image](https://user-images.githubusercontent.com/42212240/104614040-94672880-5690-11eb-8e5b-0ba71fba36ab.png)

I can play my scene locally with localhost, and I've tried to play my scene with github pages, but this is what I get:
https://ecoeditor.github.io/ParticleSystem_Level2/ 

My question is how did you manage to host your game on github pages, even though you're index.html file is in the public directory?
I've renamed my "public" directory to 'docs" and in the settings I chose "Master/docs", but its still not working.

Thank you.

**Comment by Drigax** [comment]
Good question! The game source is NOT the project that is hosted by github. I suggest creating a separate repo containing your built project bundle, and hosting that via github pages. The hosted version of the game can be found here:

https://github.com/capucat/capucat.github.io

Thanks!
