### ISSUE TITLE
Online URL cannot be opened

### ISSUE THREAD

**Issue by Jeggery** [BabylonJS/SummerFestival#6]
[https://capucat.github.io/summers-festival/](url)
Error when opening this website.
The screenshot is as follows: 
![22322](https://user-images.githubusercontent.com/39072827/167385143-65262b51-3cea-4714-881f-4b3e1133639e.png)

**Comment by Corysia** [comment]
Discussed and fix at https://forum.babylonjs.com/t/the-create-a-game-tutorial-series-from-docs-fails-to-compile/37098

**Comment by RaananW** [comment]
Hosted now at https://babylonjs.github.io/SummerFestival/
